apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: stream-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: stream-team-api-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: stream-team-config
                  key: SERVER_PORT_API_GATEWAY
            - name: MOVIE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: stream-team-config
                  key: MOVIE_SERVICE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: stream-team-config
                  key: AUTH_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: stream-team-config
                  key: USER_SERVICE_URL
            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: stream-team-config
                  key: CORS_ALLOWED_ORIGINS
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 750m
              memory: 768Mi
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: stream-team
spec:
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
