apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stream-team
resources:
  - namespace.yaml
  - configmap.yaml
  - mongodb.yaml
  - backend.yaml
  - movie-service.yaml
  - api-gateway.yaml
  - frontend.yaml
  - ingress.yaml
