apiVersion: v1
kind: Secret
metadata:
  name: stream-team-secrets
  namespace: stream-team
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongodb:27017/stream_db"
  TMDB_API_KEY: "replace-me"
  TMDB_READ_ACCESS_KEY: "replace-me"
  PAYSTACK_SECRET_KEY: "replace-me"
  PAYSTACK_CALLBACK_URL: "https://stream-team.example.com/payment/callback"
  MAIL_USERNAME: "replace-me@example.com"
  MAIL_APP_PASSWORD: "replace-me"
