spring.application.name=backend

server.port=8080

#MongoDB 
spring.data.mongodb.uri=mongodb+srv://joan:<db_password>@cluster0.0fat0q1.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=stream_db

# Paystack
paystack.secret-key=${sk_test_4139d13f94999f28677553d3d226a71fe7c820b6}
paystack.base-url=https://api.paystack.co
